language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.8-dev"
  - "3.9-dev"

install:
  - pip3 install -r requirements.txt

script:
  - python3 aquacheck.py

after_success:
  - bash <(curl -s https://codecov.io/bash)