version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: |
            pip3 install coverage
            pip3 install -r ./requirements.txt
            python3 aquacheck.py test
            coverage run aquacheck.py
            coverage report -m
            coverage html
          name: Aqua Service Check

workflows:
  main:
    jobs:
      - build-and-test
